### ISSUE TITLE
Leave command

### ISSUE THREAD

**Issue by jreppnow** [Piturnah/jp-wordle-bot#7]
Implement a !leave command, including the corresponding logic. 

- if a player leaves while it is their turn, the next player's turn needs to be triggered. 
- if the host leaves, another player needs to be promoted to host 
- if all players leave, the Session needs to be deleted

**Comment by Piturnah** [comment]
Sorry, I meant to do implement #6 for fed532a, 
fed532a not relevant to this issue.

**Comment by jreppnow** [comment]
Leave command in lobby was implemented in 0.0.1. However, it seems desirable to provide a leave command during an ongoing game as well.

**Comment by jreppnow** [comment]
Implemented fully (including leaving during ongoing games) in 0.0.3: https://github.com/Piturnah/jp-wordle-bot/releases/tag/0.0.3
